### ISSUE TITLE
Write documentation for the official zkSync era Docs website

### ISSUE THREAD

**Issue by mationorato** [lambdaclass/zksync-web3-rs#96]
Add general docs and starting guide (already available in the readme file) about how to use the basic features to [zkSync-docs ](https://github.com/matter-labs/zksync-web-era-docs) project.

**Comment by jpcenteno** [comment]
I fixed the repo URL, which was pointing to zksync 1.0 instead of Era

**Comment by jpcenteno** [comment]
Here's my PR feat: [add rust sdk documentation #697](https://github.com/matter-labs/zksync-web-era-docs/pull/697)

**Comment by jpcenteno** [comment]
Closing this issue because my PR was merged.
